language: java
install: true
 
dist: precise

sudo: required

before_install:
 - chmod +x ./gradlew
 
before_script:
  - chmod +x gradlew
  - echo "We can put normal shell commands here"
  
jdk:
  - oraclejdk8


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "build/libs/leadwire-1.13-SNAPSHOT-aspectj.jar"
  skip_cleanup: true
  on:
    tags: true


script:
    - gradle TravisCI -x test
